name: holoviz_wasm
channels:
  - conda-forge
dependencies:
  - python=3.10
  # Core HoloViz stack - only what we need for WASM
  - panel=1.6.0
  - datashader
  - param
  - colorcet
  # Data & Computation
  - numpy
  - pandas
  # Build tools
  - pyodide-build
  # Development tools
  - jupyter_bokeh
  - ipykernel
  - watchfiles
